repos:
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        exclude: ^(.*/migrations/|manage.py|settings.py)

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: ^(.*/migrations/|manage.py|settings.py)
